tor-address:
  name: Tor Address
  description: The Tor address.
  type: pointer
  subtype: package
  package-id: syncthing
  target: tor-address
  interface: main

username:
  type: string
  name: Username
  description: The user for loging into the administration page of syncthing
  nullable: false
  copyable: true
  masked: false
  default: "admin"

password:
  type: string
  name: Password
  description: The password for loging into the administration page of syncthing
  nullable: false
  copyable: true
  masked: true
  default:
    charset: "a-z,A-Z,0-9"
    len: 22

default_folder:
  type: object
  name: Default Folder
  description: This is the default folder that the syncthing cares about
  nullable: false
  spec:
    path:
      type: string
      name: Path
      description: This is the location of the default folder
      pattern: "^(\\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)(/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)*/?$"
      default: "Sync"
      nullable: false

folders:
  type: list
  name: Folders
  description: The extra folders we want to server
  default: []
  range: "[0, *)"
  subtype: object
  spec:
    unique-by: name
    display-as: "{{name}}"
    spec:
      name:
        type: string
        nullable: false
        name: Subdomain name
        description: The subdomain of your Embassy Pages .onion address to host the website on. For example, a value of "me" would produce a website hosted at http://me.myaddress.onion.
        pattern: "^[a-z-]+$"
        pattern-description: "May contain only lowercase characters and hyphens"
      path:
        type: string
        name: Directory Path
        description: The path to the directory in Syncthing that contains the synced files. For example, a value of "websites/resume_site" would tell Syncthing to look for that directory in File Browser.
        pattern: "^(\\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)(/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)*/?$"
        pattern-description: Must be a valid relative file path
        nullable: false
